services:
  binance-us-btcusdt-collector:
    build: .
    command: ./entrypoint.sh
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@172.21.0.2:5432/indexer?schema=public
    networks:
      - indector

networks:
  indector: {}
